/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SafetySymbolRouteImport } from './routes/safety.$symbol'
import { Route as CommoditySymbolRouteImport } from './routes/commodity.$symbol'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetySymbolRoute = SafetySymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => SafetyRoute,
} as any)
const CommoditySymbolRoute = CommoditySymbolRouteImport.update({
  id: '/commodity/$symbol',
  path: '/commodity/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/safety': typeof SafetyRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/commodity/$symbol': typeof CommoditySymbolRoute
  '/safety/$symbol': typeof SafetySymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/safety': typeof SafetyRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/commodity/$symbol': typeof CommoditySymbolRoute
  '/safety/$symbol': typeof SafetySymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/safety': typeof SafetyRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/commodity/$symbol': typeof CommoditySymbolRoute
  '/safety/$symbol': typeof SafetySymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/safety'
    | '/watchlist'
    | '/commodity/$symbol'
    | '/safety/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/safety'
    | '/watchlist'
    | '/commodity/$symbol'
    | '/safety/$symbol'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/safety'
    | '/watchlist'
    | '/commodity/$symbol'
    | '/safety/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  SafetyRoute: typeof SafetyRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  CommoditySymbolRoute: typeof CommoditySymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/$symbol': {
      id: '/safety/$symbol'
      path: '/$symbol'
      fullPath: '/safety/$symbol'
      preLoaderRoute: typeof SafetySymbolRouteImport
      parentRoute: typeof SafetyRoute
    }
    '/commodity/$symbol': {
      id: '/commodity/$symbol'
      path: '/commodity/$symbol'
      fullPath: '/commodity/$symbol'
      preLoaderRoute: typeof CommoditySymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SafetyRouteChildren {
  SafetySymbolRoute: typeof SafetySymbolRoute
}

const SafetyRouteChildren: SafetyRouteChildren = {
  SafetySymbolRoute: SafetySymbolRoute,
}

const SafetyRouteWithChildren =
  SafetyRoute._addFileChildren(SafetyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  SafetyRoute: SafetyRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  CommoditySymbolRoute: CommoditySymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
